[project]
name = "jarvis-cloud-native"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "flask>=3.1.0",
    "openai-agents>=0.0.13",
    "pykube-ng>=23.6.0",
]
